import type { DatabaseConnection } from '../connection';

/**
 * テスト用の馬データを投入する。
 * 10頭の馬（祖先馬含む）と年度別ステータスを作成する。
 */
export async function seedTestHorses(db: DatabaseConnection): Promise<number> {
  return db.transaction(async (conn) => {
    // 系統IDを名前で引く
    async function getLineageId(name: string): Promise<number | null> {
      const row = await conn.get<{ id: number }>('SELECT id FROM lineages WHERE name = ?', [name]);
      return row?.id ?? null;
    }

    const deepImpactLineage = await getLineageId('ディープインパクト系');
    const kingKameLineage = await getLineageId('キングカメハメハ系');
    const lordKaguraLineage = await getLineageId('ロードカナロア系');
    const heartsCryLineage = await getLineageId('ハーツクライ系');
    const stayGoldLineage = await getLineageId('ステイゴールド系');

    // 祖先馬（父・母）を先に作成
    const sires = [
      { name: 'ディープインパクト', sex: '牡', country: '日', lineageId: deepImpactLineage },
      { name: 'キングカメハメハ', sex: '牡', country: '日', lineageId: kingKameLineage },
      { name: 'ロードカナロア', sex: '牡', country: '日', lineageId: lordKaguraLineage },
      { name: 'ハーツクライ', sex: '牡', country: '日', lineageId: heartsCryLineage },
      { name: 'オルフェーヴル', sex: '牡', country: '日', lineageId: stayGoldLineage },
    ];

    const dams = [
      { name: 'ウインドインハーヘア', sex: '牝', country: '日' },
      { name: 'マンファス', sex: '牝', country: '日' },
      { name: 'レディブロンド', sex: '牝', country: '日' },
      { name: 'シーザリオ', sex: '牝', country: '日' },
      { name: 'オリエンタルアート', sex: '牝', country: '日' },
    ];

    const sireIds: number[] = [];
    for (const s of sires) {
      const result = await conn.run(
        "INSERT INTO horses (name, sex, country, status, lineage_id, is_historical) VALUES (?, ?, ?, 'ancestor', ?, 1)",
        [s.name, s.sex, s.country, s.lineageId],
      );
      sireIds.push(result.lastInsertRowId);
    }

    const damIds: number[] = [];
    for (const d of dams) {
      const result = await conn.run(
        "INSERT INTO horses (name, sex, country, status, is_historical) VALUES (?, ?, ?, 'ancestor', 1)",
        [d.name, d.sex, d.country],
      );
      damIds.push(result.lastInsertRowId);
    }

    // 現役馬・繁殖馬データ
    const horses = [
      {
        name: 'コントレイル',
        sex: '牡',
        birthYear: 2017,
        country: '日',
        status: '種牡馬',
        sireIdx: 0,
        damIdx: 2,
        lineageId: deepImpactLineage,
        factors: ['大舞台', 'スピード'],
        mareLine: null,
      },
      {
        name: 'イクイノックス',
        sex: '牡',
        birthYear: 2019,
        country: '日',
        status: '種牡馬',
        sireIdx: 1,
        damIdx: 3,
        lineageId: kingKameLineage,
        factors: ['スピード', 'パワー'],
        mareLine: null,
      },
      {
        name: 'リバティアイランド',
        sex: '牝',
        birthYear: 2020,
        country: '日',
        status: '繁殖牝馬',
        sireIdx: 0,
        damIdx: 1,
        lineageId: deepImpactLineage,
        factors: ['スピード'],
        mareLine: null,
      },
      {
        name: 'ドウデュース',
        sex: '牡',
        birthYear: 2019,
        country: '日',
        status: '現役',
        sireIdx: 3,
        damIdx: 4,
        lineageId: heartsCryLineage,
        factors: ['根幹距離', 'スタミナ'],
        mareLine: null,
      },
      {
        name: 'スターズオンアース',
        sex: '牝',
        birthYear: 2019,
        country: '日',
        status: '繁殖牝馬',
        sireIdx: 0,
        damIdx: 0,
        lineageId: deepImpactLineage,
        factors: ['スピード'],
        mareLine: null,
      },
      {
        name: 'タスティエーラ',
        sex: '牡',
        birthYear: 2020,
        country: '日',
        status: '現役',
        sireIdx: 2,
        damIdx: 1,
        lineageId: lordKaguraLineage,
        factors: ['パワー', 'スピード'],
        mareLine: null,
      },
      {
        name: 'ソールオリエンス',
        sex: '牡',
        birthYear: 2020,
        country: '日',
        status: '現役',
        sireIdx: 1,
        damIdx: 4,
        lineageId: kingKameLineage,
        factors: ['スタミナ'],
        mareLine: null,
      },
      {
        name: 'レガレイラ',
        sex: '牝',
        birthYear: 2021,
        country: '日',
        status: '現役',
        sireIdx: 2,
        damIdx: 3,
        lineageId: lordKaguraLineage,
        factors: ['大舞台', 'スピード'],
        mareLine: null,
      },
      {
        name: 'ジャスティンミラノ',
        sex: '牡',
        birthYear: 2021,
        country: '日',
        status: '現役',
        sireIdx: 1,
        damIdx: 2,
        lineageId: kingKameLineage,
        factors: ['スピード'],
        mareLine: null,
      },
      {
        name: 'アーバンシック',
        sex: '牡',
        birthYear: 2021,
        country: '日',
        status: '現役',
        sireIdx: 4,
        damIdx: 0,
        lineageId: stayGoldLineage,
        factors: ['スタミナ', 'パワー'],
        mareLine: null,
      },
    ];

    const horseIds: number[] = [];
    for (const h of horses) {
      const result = await conn.run(
        'INSERT INTO horses (name, sex, birth_year, country, status, sire_id, dam_id, lineage_id, factors, is_historical) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0)',
        [
          h.name,
          h.sex,
          h.birthYear,
          h.country,
          h.status,
          sireIds[h.sireIdx],
          damIds[h.damIdx],
          h.lineageId,
          JSON.stringify(h.factors),
        ],
      );
      horseIds.push(result.lastInsertRowId);
    }

    // 年度別ステータス
    const statuses = [
      {
        idx: 0,
        year: 2025,
        sp: 'S',
        spV: 3,
        pow: 'A+',
        powV: 8,
        inst: 'A',
        instV: 12,
        sta: 'A',
        staV: 10,
        men: 'B+',
        menV: 15,
        wis: 'A',
        wisV: 11,
        turf: '◎',
        dirt: '○',
        dMin: 1800,
        dMax: 2400,
        growth: '普通',
        style: ['先行'],
        record: '11-8-1-0',
      },
      {
        idx: 1,
        year: 2025,
        sp: 'S+',
        spV: 0,
        pow: 'S',
        powV: 2,
        inst: 'A+',
        instV: 6,
        sta: 'A+',
        staV: 7,
        men: 'A',
        menV: 10,
        wis: 'S',
        wisV: 1,
        turf: '◎',
        dirt: '△',
        dMin: 1600,
        dMax: 2500,
        growth: '普通',
        style: ['先行', '差'],
        record: '10-8-0-0',
      },
      {
        idx: 2,
        year: 2025,
        sp: 'S',
        spV: 4,
        pow: 'A',
        powV: 11,
        inst: 'A+',
        instV: 8,
        sta: 'A',
        staV: 12,
        men: 'A',
        menV: 13,
        wis: 'A+',
        wisV: 9,
        turf: '◎',
        dirt: '△',
        dMin: 1400,
        dMax: 2400,
        growth: '早熟',
        style: ['差'],
        record: '8-6-1-0',
      },
      {
        idx: 3,
        year: 2025,
        sp: 'A+',
        spV: 7,
        pow: 'A+',
        powV: 6,
        inst: 'A',
        instV: 14,
        sta: 'S',
        staV: 3,
        men: 'A+',
        menV: 8,
        wis: 'A',
        wisV: 14,
        turf: '◎',
        dirt: '○',
        dMin: 1800,
        dMax: 3000,
        growth: '遅咲',
        style: ['差', '追込'],
        record: '14-7-2-1',
      },
      {
        idx: 4,
        year: 2025,
        sp: 'A+',
        spV: 9,
        pow: 'A',
        powV: 13,
        inst: 'A',
        instV: 15,
        sta: 'A',
        staV: 14,
        men: 'B+',
        menV: 16,
        wis: 'A',
        wisV: 12,
        turf: '◎',
        dirt: '△',
        dMin: 1600,
        dMax: 2400,
        growth: '普通',
        style: ['先行'],
        record: '9-5-2-0',
      },
      {
        idx: 5,
        year: 2025,
        sp: 'A',
        spV: 12,
        pow: 'A+',
        powV: 7,
        inst: 'A',
        instV: 10,
        sta: 'A+',
        staV: 8,
        men: 'A',
        menV: 11,
        wis: 'B+',
        wisV: 17,
        turf: '◎',
        dirt: '○',
        dMin: 1800,
        dMax: 2600,
        growth: '普通',
        style: ['先行'],
        record: '7-3-1-1',
      },
      {
        idx: 6,
        year: 2025,
        sp: 'A',
        spV: 14,
        pow: 'A',
        powV: 12,
        inst: 'B+',
        instV: 18,
        sta: 'A+',
        staV: 6,
        men: 'A',
        menV: 10,
        wis: 'A',
        wisV: 13,
        turf: '◎',
        dirt: '△',
        dMin: 2000,
        dMax: 2800,
        growth: '普通',
        style: ['差'],
        record: '7-3-2-0',
      },
      {
        idx: 7,
        year: 2025,
        sp: 'A+',
        spV: 8,
        pow: 'A',
        powV: 10,
        inst: 'A+',
        instV: 7,
        sta: 'A',
        staV: 11,
        men: 'A+',
        menV: 9,
        wis: 'A',
        wisV: 10,
        turf: '◎',
        dirt: '○',
        dMin: 1600,
        dMax: 2500,
        growth: '普通',
        style: ['差', '追込'],
        record: '6-4-1-0',
      },
      {
        idx: 8,
        year: 2025,
        sp: 'A+',
        spV: 6,
        pow: 'A',
        powV: 14,
        inst: 'A',
        instV: 11,
        sta: 'A',
        staV: 13,
        men: 'A',
        menV: 12,
        wis: 'B+',
        wisV: 16,
        turf: '◎',
        dirt: '△',
        dMin: 1600,
        dMax: 2000,
        growth: '早熟',
        style: ['先行'],
        record: '5-3-1-0',
      },
      {
        idx: 9,
        year: 2025,
        sp: 'A',
        spV: 13,
        pow: 'A',
        powV: 11,
        inst: 'A',
        instV: 12,
        sta: 'A+',
        staV: 5,
        men: 'B+',
        menV: 17,
        wis: 'A',
        wisV: 14,
        turf: '◎',
        dirt: '△',
        dMin: 2000,
        dMax: 3000,
        growth: '遅咲',
        style: ['差'],
        record: '5-2-2-0',
      },
    ];

    for (const s of statuses) {
      await conn.run(
        `INSERT INTO yearly_statuses (
          horse_id, year, sp_rank, sp_value, power_rank, power_value,
          instant_rank, instant_value, stamina_rank, stamina_value,
          mental_rank, mental_value, wisdom_rank, wisdom_value,
          turf_aptitude, dirt_aptitude, distance_min, distance_max,
          growth_type, running_style, race_record
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          horseIds[s.idx],
          s.year,
          s.sp,
          s.spV,
          s.pow,
          s.powV,
          s.inst,
          s.instV,
          s.sta,
          s.staV,
          s.men,
          s.menV,
          s.wis,
          s.wisV,
          s.turf,
          s.dirt,
          s.dMin,
          s.dMax,
          s.growth,
          JSON.stringify(s.style),
          s.record,
        ],
      );
    }

    return horses.length;
  });
}
