/**
 * Test fixtures for TSV parser tests.
 * Column indices match the real 読専 TSV header (69 columns, 0-68).
 */

// Column indices (from the header)
const COL = {
  NAME: 0,
  COUNTRY: 1,
  AGE: 2,
  SEX: 3,
  SP: 4,
  ST: 5,
  SP_RATIO: 6,
  POWER: 7,
  INSTANT: 8,
  STAMINA: 9,
  FLEX: 10,
  MENTAL: 11,
  WISDOM: 12,
  HEALTH: 13,
  SUB: 14,
  TURF: 15,
  DIRT: 16,
  TURF_Q: 17,
  DISTANCE: 18,
  TEMPER: 19,
  STYLE: 20,
  GROWTH: 21,
  GROW_POW: 22,
  GROW_DEG: 23,
  GROW_LIM: 24,
  LIFE: 25,
  FORM: 26,
  FATIGUE: 27,
  FIGHT: 28,
  WEIGHT: 29,
  FERTILITY: 30,
  COAT: 31,
  PERSONALITY: 32,
  HIGH: 33,
  LONG: 34,
  JUMP: 35,
  SMALL: 36,
  LEFT: 37,
  RIGHT: 38,
  LEG: 39,
  THROAT: 40,
  BACK: 41,
  SLOW: 42,
  TRAITS: 43,
  RELATION: 44,
  SIRE: 45,
  SIRE_LINE: 46,
  DAM: 47,
  MARE_LINE: 48,
  STARTS: 49,
  RECORD: 50,
  PREV_RACE: 51,
  NEXT_RACE: 52,
  CLASS: 53,
  PRIZE: 54,
  BASE_PRIZE: 55,
  BORN_COUNTRY: 56,
  OWNER: 57,
  FARM: 58,
  TRAINER: 59,
  JOCKEY: 60,
  OVERSEAS: 61,
  ACTIVE: 62,
  HISTORICAL: 63,
  HIST_NUM: 64,
  ABILITY_NUM: 65,
  HORSE_NUM: 66,
  INHERIT: 67,
  NAME_DUP: 68,
} as const;

const TOTAL_COLS = 69;

/** Build a TSV row from sparse column data. Unset columns default to empty string. */
function buildRow(data: Record<number, string>): string {
  const cells: string[] = Array(TOTAL_COLS).fill('');
  for (const [idx, val] of Object.entries(data)) {
    cells[Number(idx)] = val;
  }
  return cells.join('\t');
}

// Header row
export const HEADER_ROW = buildRow({
  [COL.NAME]: '馬名',
  [COL.COUNTRY]: '国',
  [COL.AGE]: '年',
  [COL.SEX]: '性',
  [COL.SP]: 'SP',
  [COL.ST]: 'ST',
  [COL.SP_RATIO]: 'SP率',
  [COL.POWER]: '力',
  [COL.INSTANT]: '瞬',
  [COL.STAMINA]: '勝',
  [COL.FLEX]: '柔',
  [COL.MENTAL]: '精',
  [COL.WISDOM]: '賢',
  [COL.HEALTH]: '健',
  [COL.SUB]: 'サ',
  [COL.TURF]: '芝',
  [COL.DIRT]: 'ダ',
  [COL.TURF_Q]: '芝質',
  [COL.DISTANCE]: '距離適性',
  [COL.TEMPER]: '気',
  [COL.STYLE]: '脚質',
  [COL.GROWTH]: '成型',
  [COL.GROW_POW]: '成力',
  [COL.GROW_DEG]: '成度',
  [COL.GROW_LIM]: '成限',
  [COL.LIFE]: '寿命',
  [COL.FORM]: '調子',
  [COL.FATIGUE]: '疲労',
  [COL.FIGHT]: '闘',
  [COL.WEIGHT]: '馬体重',
  [COL.FERTILITY]: '子出',
  [COL.COAT]: '毛色',
  [COL.PERSONALITY]: '性格',
  [COL.HIGH]: '高',
  [COL.LONG]: '長',
  [COL.JUMP]: '跳',
  [COL.SMALL]: '小',
  [COL.LEFT]: '左',
  [COL.RIGHT]: '右',
  [COL.LEG]: '脚',
  [COL.THROAT]: '喉',
  [COL.BACK]: '腰',
  [COL.SLOW]: '遅',
  [COL.TRAITS]: '特性',
  [COL.RELATION]: '関係性効果',
  [COL.SIRE]: '父馬',
  [COL.SIRE_LINE]: '父系',
  [COL.DAM]: '母馬',
  [COL.MARE_LINE]: '牝系',
  [COL.STARTS]: '出走',
  [COL.RECORD]: '戦績',
  [COL.PREV_RACE]: '前走',
  [COL.NEXT_RACE]: '次走',
  [COL.CLASS]: 'クラス',
  [COL.PRIZE]: '賞金',
  [COL.BASE_PRIZE]: '本賞金',
  [COL.BORN_COUNTRY]: '生産国',
  [COL.OWNER]: '馬主',
  [COL.FARM]: '牧場',
  [COL.TRAINER]: '調教師',
  [COL.JOCKEY]: '騎手',
  [COL.OVERSEAS]: '海外遠征',
  [COL.ACTIVE]: '現役',
  [COL.HISTORICAL]: '史実',
  [COL.HIST_NUM]: '史実番号',
  [COL.ABILITY_NUM]: '能力番号',
  [COL.HORSE_NUM]: '馬番号',
  [COL.INHERIT]: '継承特性',
  [COL.NAME_DUP]: '馬名',
});

// Common fields helper
function horse(
  name: string,
  country: string,
  age: string,
  sex: string,
  sp: string,
  power: string,
  instant: string,
  stamina: string,
  mental: string,
  wisdom: string,
  turf: string,
  dirt: string,
  distance: string,
  style: string,
  growth: string,
  traits: string,
  relation: string,
  sire: string,
  sireLine: string,
  dam: string,
  mareLine: string,
  record: string,
  jockey: string,
  extras?: Partial<Record<number, string>>,
): string {
  return buildRow({
    [COL.NAME]: name,
    [COL.COUNTRY]: country,
    [COL.AGE]: age,
    [COL.SEX]: sex,
    [COL.SP]: sp,
    [COL.POWER]: power,
    [COL.INSTANT]: instant,
    [COL.STAMINA]: stamina,
    [COL.MENTAL]: mental,
    [COL.WISDOM]: wisdom,
    [COL.TURF]: turf,
    [COL.DIRT]: dirt,
    [COL.DISTANCE]: distance,
    [COL.STYLE]: style,
    [COL.GROWTH]: growth,
    [COL.TRAITS]: traits,
    [COL.RELATION]: relation,
    [COL.SIRE]: sire,
    [COL.SIRE_LINE]: sireLine,
    [COL.DAM]: dam,
    [COL.MARE_LINE]: mareLine,
    [COL.RECORD]: record,
    [COL.JOCKEY]: jockey,
    [COL.ACTIVE]: '○',
    [COL.NAME_DUP]: name.replace(/^\(外\)/, ''),
    ...extras,
  });
}

// All 22 rows from the user's real data
export const DATA_ROWS = [
  // 0: シーザジュピター - 日/牝/5歳, 追込, 早鍋, 特性あり, 海外遠征済
  horse(
    'シーザジュピター',
    '日',
    '5',
    '牝',
    '83(82)',
    'S+(0)',
    'B(1)',
    'D+(1)',
    'A+(2)',
    'D(6)',
    '◎',
    '◎',
    '1100～2000m',
    '追込',
    '早鍋',
    '大舞台 鉄砲 牡馬混合 直一気',
    '闘 学',
    'シーザスターズ',
    'グリーンデザート系',
    'カンパリジュピター',
    '',
    '14 -  3 -  0 -  0',
    '188',
    { [COL.OVERSEAS]: '済' },
  ),
  // 1: ジンキヨモト - 米/牡/4歳, 差し, 普遅, △芝, 短距離
  horse(
    'ジンキヨモト',
    '米',
    '4',
    '牡',
    '82(79)',
    'S+(1)',
    'B+(1)',
    'F(2)',
    'A(6)',
    'A+(4)',
    '△',
    '◎',
    '1100～1500m',
    '差し',
    '普遅',
    '叩き良化',
    '身P',
    'ディクタット',
    'マンノウォー系',
    'ジンクリリン',
    'エスサーディー系',
    ' 6 -  1 -  2 -  1',
    '571',
  ),
  // 2: ジンビーズ - 日/牝/3歳, 先行, 普早, 長距離, 牝系あり
  horse(
    'ジンビーズ',
    '日',
    '3',
    '牝',
    '82(78)',
    'E(0)',
    'A+(0)',
    'S+(0)',
    'S(0)',
    'G(0)',
    '◎',
    '◎',
    '1500～2700m',
    '先行',
    '普早',
    'スタート',
    '',
    'キングカメハメハ',
    'キングマンボ系',
    'ジンチョウウン',
    'ドクサ系',
    ' 3 -  0 -  0 -  0',
    '230',
  ),
  // 3: ジンタクト - 欧/牡/5歳, 先行, 普鍋
  horse(
    'ジンタクト',
    '欧',
    '5',
    '牡',
    '81(74)',
    'D+(4)',
    'G+(2)',
    'B+(1)',
    'S(6)',
    'B+(6)',
    '◎',
    '◎',
    '1500～1700m',
    '先行',
    '普鍋',
    '二の脚',
    '調 精S',
    'ディクタット',
    'マンノウォー系',
    'ブロードシャルール',
    'ブロードシャルール系',
    ' 9 -  3 -  0 -  3',
    '622',
  ),
  // 4: ジンヒジリ - 日/牝/4歳, 差し, 普遅, ×ダ, 特性なし, 海外遠征済
  horse(
    'ジンヒジリ',
    '日',
    '4',
    '牝',
    '80(78)',
    'D+(0)',
    'C+(2)',
    'C(3)',
    'S(0)',
    'C(3)',
    '◎',
    '×',
    '2000～2200m',
    '差し',
    '普遅',
    '',
    '',
    'グラスワンダー',
    'ロベルト系',
    'ジンコントラバス',
    'エスサーディー系',
    ' 5 -  2 -  2 -  2',
    '355',
    { [COL.OVERSEAS]: '済' },
  ),
  // 5: ジンタキモト - 米/牡/4歳, 差し, 普早
  horse(
    'ジンタキモト',
    '米',
    '4',
    '牡',
    '78(76)',
    'A(1)',
    'B(3)',
    'C+(1)',
    'S+(8)',
    'B+(3)',
    '◎',
    '◎',
    '1800～2000m',
    '差し',
    '普早',
    'スタート',
    '身P',
    'ドバイミレニアム',
    'ドバイミレニアム系',
    'ジンキュウリ',
    'ドクサ系',
    ' 5 -  4 -  0 -  2',
    '610',
  ),
  // 6: (外)ジンショウドウ - (外)プレフィックス, 追込, 普早, ○ダ, 腰×
  horse(
    '(外)ジンショウドウ',
    '日',
    '3',
    '牡',
    '78(75)',
    'S+(2)',
    'S(0)',
    'C+(0)',
    'A(1)',
    'S(1)',
    '◎',
    '○',
    '1900～2100m',
    '追込',
    '普早',
    '',
    '',
    'ジャイアンツコーズウェイ',
    'ストームキャット系',
    'ジンワシントン',
    '',
    ' 4 -  0 -  0 -  0',
    '344',
    { [COL.BACK]: '×' },
  ),
  // 7: ジンオクイ - 日/牡/4歳, 逃げ, 超晩, ×ダ, 関係性効果のみ
  horse(
    'ジンオクイ',
    '日',
    '4',
    '牡',
    '78(77)',
    'G(0)',
    'D(1)',
    'S(0)',
    'A(4)',
    'A(1)',
    '◎',
    '×',
    '1500～2000m',
    '逃げ',
    '超晩',
    '',
    '精K',
    'オークションホーム',
    'カーレッド系',
    'ジンバイオリン',
    'ジョーセイバー系',
    ' 3 -  1 -  1 -  1',
    '198',
  ),
  // 8: (外)ジントモザワ - (外)プレフィックス, 先行, 普遅, 海外遠征済
  horse(
    '(外)ジントモザワ',
    '日',
    '4',
    '牡',
    '76(73)',
    'S(3)',
    'C(3)',
    'B(3)',
    'C(1)',
    'C+(7)',
    '◎',
    '◎',
    '1500～1900m',
    '先行',
    '普遅',
    '鉄砲 スタート',
    '闘',
    'エルコンドルパサー',
    'エルコンドルパサー系',
    'ジンブリ',
    'ジョーセイバー系',
    ' 8 -  1 -  1 -  1',
    '176',
    { [COL.OVERSEAS]: '済' },
  ),
  // 9: シーザサン - 欧/牡/5歳, 差し, 覚醒, 3特性, 海外遠征済
  horse(
    'シーザサン',
    '欧',
    '5',
    '牡',
    '76(72)',
    'S+(2)',
    'S+(2)',
    'A+(1)',
    'F(3)',
    'S+(2)',
    '◎',
    '×',
    '1300～2600m',
    '差し',
    '覚醒',
    '大舞台 直一気 学習能力',
    '調 疲 精K',
    'シーザスターズ',
    'グリーンデザート系',
    'ジンサンシャイン',
    'リメンブランス系',
    '14 -  2 -  0 -  2',
    '662',
    { [COL.OVERSEAS]: '済' },
  ),
  // 10: ジンライアー - 米/牡/3歳, 差し, 普早, ○芝, 特性なし
  horse(
    'ジンライアー',
    '米',
    '3',
    '牡',
    '76(75)',
    'F+(3)',
    'S+(2)',
    'E+(0)',
    'C+(10)',
    'A(2)',
    '○',
    '◎',
    '1600～2800m',
    '差し',
    '普早',
    '',
    '',
    'グラスワンダー',
    'ロベルト系',
    'マイグッドネス',
    '',
    ' 3 -  1 -  0 -  0',
    '795',
  ),
  // 11: (外)ジンパピヨン - (外)プレフィックス, 差し, 超晩
  horse(
    '(外)ジンパピヨン',
    '日',
    '4',
    '牡',
    '76(74)',
    'F+(6)',
    'S(7)',
    'B+(1)',
    'B+(0)',
    'A(3)',
    '◎',
    '○',
    '1400～1800m',
    '差し',
    '超晩',
    '鉄砲',
    '',
    'ドバイミレニアム',
    'ドバイミレニアム系',
    'ジンヴィーナス',
    'エール系',
    ' 4 -  1 -  0 -  1',
    '354',
  ),
  // 12: ジンモーテル - 米/牡/3歳, 先行, 普遅, △芝, 未出走
  horse(
    'ジンモーテル',
    '米',
    '3',
    '牡',
    '76(71)',
    'D+(2)',
    'G(0)',
    'C+(2)',
    'A(0)',
    'A+(4)',
    '△',
    '◎',
    '1200～1200m',
    '先行',
    '普遅',
    '',
    '',
    'ドリームアヘッド',
    'マンノウォー系',
    'ラグジャリー',
    '',
    ' 0 -  0 -  0 -  0',
    '795',
    { [COL.PREV_RACE]: '未出走', [COL.CLASS]: '未勝利' },
  ),
  // 13: ジンハダシノメガミ - 欧/牝/3歳, 先行, 普遅, 未出走
  horse(
    'ジンハダシノメガミ',
    '欧',
    '3',
    '牝',
    '76(74)',
    'S+(2)',
    'E+(0)',
    'C(1)',
    'E+(1)',
    'C(5)',
    '◎',
    '○',
    '1600～2000m',
    '先行',
    '普遅',
    '',
    '',
    'ガリレオ',
    'ガリレオ系',
    'ジンハスケル',
    '',
    ' 0 -  0 -  0 -  0',
    '795',
    { [COL.PREV_RACE]: '未出走', [COL.CLASS]: '未勝利' },
  ),
  // 14: ジンイカリ - 日/牡/4歳, 自在, 早鍋, 海外遠征済
  horse(
    'ジンイカリ',
    '日',
    '4',
    '牡',
    '75(73)',
    'F(1)',
    'A+(4)',
    'S+(4)',
    'C+(2)',
    'S+(2)',
    '○',
    '○',
    '1700～2900m',
    '自在',
    '早鍋',
    '鉄砲',
    '調 寿 精S',
    'グラスワンダー',
    'ロベルト系',
    'ジンイマガワ',
    'モフィーダ系',
    ' 8 -  0 -  1 -  1',
    '175',
    { [COL.OVERSEAS]: '済' },
  ),
  // 15: (外)ジンジュース - (外)プレフィックス, 牝/3歳, 差し, 普遅
  horse(
    '(外)ジンジュース',
    '日',
    '3',
    '牝',
    '75(72)',
    'S(5)',
    'S+(0)',
    'C+(0)',
    'A(3)',
    'B+(2)',
    '◎',
    '◎',
    '1800～2300m',
    '差し',
    '普遅',
    '',
    '',
    'タピット',
    'プルピット系',
    'ジンキュウリ',
    'ドクサ系',
    ' 3 -  1 -  0 -  0',
    '188',
  ),
  // 16: ジンドレンテ - 欧/牝/5歳, 差し, 普遅, 2特性, 海外遠征済
  horse(
    'ジンドレンテ',
    '欧',
    '5',
    '牝',
    '74(72)',
    'A(2)',
    'S+(0)',
    'A+(1)',
    'C+(0)',
    'S+(2)',
    '◎',
    '○',
    '1300～2400m',
    '差し',
    '普遅',
    '大舞台 叩き良化',
    '',
    'ドバイミレニアム',
    'ドバイミレニアム系',
    'ジンコロンビア',
    '',
    ' 7 -  5 -  1 -  3',
    '656',
    { [COL.OVERSEAS]: '済' },
  ),
  // 17: ジンアオイ - 日/牝/4歳, 先行, 普遅, ×ダ, 2特性
  horse(
    'ジンアオイ',
    '日',
    '4',
    '牝',
    '74(72)',
    'S+(0)',
    'S+(2)',
    'S+(2)',
    'F(1)',
    'B(4)',
    '◎',
    '×',
    '1300～2500m',
    '先行',
    '普遅',
    'スタート 完全燃焼',
    '',
    'グラスワンダー',
    'ロベルト系',
    'ジンネギ',
    'エスサーディー系',
    ' 6 -  0 -  2 -  0',
    '302',
  ),
  // 18: ジンサイガ - 欧/牡/4歳, 逃げ, 覚醒, 特性なし
  horse(
    'ジンサイガ',
    '欧',
    '4',
    '牡',
    '73(71)',
    'S(0)',
    'B(0)',
    'B(0)',
    'B+(3)',
    'D+(2)',
    '○',
    '○',
    '1700～2600m',
    '逃げ',
    '覚醒',
    '',
    '',
    'シーザスターズ',
    'グリーンデザート系',
    'ショカツリョウ',
    'モフィーダ系',
    ' 2 -  1 -  0 -  7',
    '620',
  ),
  // 19: ジンアオイダンガン - 日/牡/3歳, 差し, 早熟, ×ダ
  horse(
    'ジンアオイダンガン',
    '日',
    '3',
    '牡',
    '72(70)',
    'S(0)',
    'S(0)',
    'C(1)',
    'E+(0)',
    'A+(1)',
    '◎',
    '×',
    '1400～2300m',
    '差し',
    '早熟',
    '',
    '',
    'シーザスターズ',
    'グリーンデザート系',
    'ジンコトリン',
    '',
    ' 4 -  1 -  0 -  0',
    '250',
  ),
  // 20: ジンブロウィン - 日/牡/3歳, 差し, 普遅, △ダ
  horse(
    'ジンブロウィン',
    '日',
    '3',
    '牡',
    '69(67)',
    'S(0)',
    'S+(4)',
    'A(2)',
    'C(1)',
    'G+(2)',
    '◎',
    '△',
    '2000～2500m',
    '差し',
    '普遅',
    '',
    '',
    'キングカメハメハ',
    'キングマンボ系',
    'カンパリダラジナ',
    '',
    ' 2 -  0 -  0 -  0',
    '176',
  ),
  // 21: ジンウチョウテン - 日/牡/3歳, 差し, 普遅, ×芝
  horse(
    'ジンウチョウテン',
    '日',
    '3',
    '牡',
    '69(67)',
    'E(0)',
    'S(0)',
    'A(0)',
    'C(0)',
    'D(0)',
    '×',
    '◎',
    '1300～1900m',
    '差し',
    '普遅',
    '',
    '',
    'オークションホーム',
    'カーレッド系',
    'ジンジャズ',
    'ジョーセイバー系',
    ' 2 -  1 -  0 -  0',
    '230',
  ),
];

/** Build a full TSV string with trailing tabs (matching real 読専 output). */
export function buildFullTsv(): string {
  return [HEADER_ROW + '\t', ...DATA_ROWS.map((r) => r + '\t')].join('\n');
}

/** Build a full TSV string without trailing tabs. */
export function buildFullTsvNoTrailingTab(): string {
  return [HEADER_ROW, ...DATA_ROWS].join('\n');
}
